# petclinic-frontend

apiVersion: apps/v1
kind: Deployment
metadata:
 name: petclinic-fe
 labels:
     # app: petclinic-fe
     # tier: frontend
     # track: stable
spec:
  # serviceName: petclinic-fe
  replicas: 1
  # updateStrategy:
    # type: RollingUpdate
  selector:
    matchLabels:
      app: petclinic-be
      tier: frontend
      track: stable
  template:
    metadata:
     # name: petclinic-fe
     labels:
       app: petclinic-be
       tier: frontend
       track: stable
    spec:
      # terminationGracePeriodSeconds: 10
      containers:
      - name: petclinic-fe
        image: gcr.io/task1-260513/petclinic-fe:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
          #- containerPort: 80
          #- containerPort: 3000
          #- containerPort: 4444
          #- containerPort: 443
        env:
          - name: "PORT"
            value: "8080"


---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-fe
spec:
  type: LoadBalancer
  selector:
    app: petclinic-be
    tier: frontend
  # ensure the client ip is propagated to avoid the invalid crumb issue when using LoadBalancer (k8s >=1.7)
  # externalTrafficPolicy: Local
  ports:
    - protocol: "TCP"
      # name: http
      port: 8080
      targetPort: 8080