apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: petclinic-fe
 labels:
     app: petclinic-fe
     type: petclinic-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      type: petclinic-fe
  strategy:
    type: Recreate
  template:
    metadata:
     name: petclinic-fe
     labels:
        app: petclinic-fe
        type: petclinic-fe
    spec:
      containers:
      - name: petclinic-fe
        image: gcr.io/task1-260513/petclinic-fe:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: 8080


---
apiVersion: v1
kind: Service
metadata:
    name: service-backend
spec:
    type: NodePort
    ports:
     - targetPort: 8080
       port: 8080
       nodePort: 30016
    selector:
       app: petclinic-fe
       type: petclinic-fe
    sessionAffinity: None
    type: NodePort
